/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.hmsd;
import java.awt.*;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.JMenuItem;


/**
 *
 * @author Acer
 */
public class NewJFrame extends javax.swing.JFrame {
     private JPanel mainPanel;
   // private CardLayout cardLayout;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewJFrame.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {//constructor
        initComponents();
        
       setLocationRelativeTo(null);
       addRightClickMenu();
       
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ManageRoom = new javax.swing.JPanel();
        CheckIn = new javax.swing.JPanel();
        CheckOut = new javax.swing.JPanel();
        ReceiptBilling = new javax.swing.JPanel();
        Revenue = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableInfo = new javax.swing.JTable();
        backHomePage = new javax.swing.JButton();
        addRoom = new javax.swing.JButton();
        exitBnt = new javax.swing.JButton();
        textField1 = new java.awt.TextField();

        ManageRoom.setFocusCycleRoot(true);
        ManageRoom.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CheckIn.setPreferredSize(new java.awt.Dimension(1200, 700));

        javax.swing.GroupLayout CheckInLayout = new javax.swing.GroupLayout(CheckIn);
        CheckIn.setLayout(CheckInLayout);
        CheckInLayout.setHorizontalGroup(
            CheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        CheckInLayout.setVerticalGroup(
            CheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        CheckOut.setPreferredSize(new java.awt.Dimension(1200, 700));

        javax.swing.GroupLayout CheckOutLayout = new javax.swing.GroupLayout(CheckOut);
        CheckOut.setLayout(CheckOutLayout);
        CheckOutLayout.setHorizontalGroup(
            CheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        CheckOutLayout.setVerticalGroup(
            CheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        ReceiptBilling.setPreferredSize(new java.awt.Dimension(1200, 700));

        javax.swing.GroupLayout ReceiptBillingLayout = new javax.swing.GroupLayout(ReceiptBilling);
        ReceiptBilling.setLayout(ReceiptBillingLayout);
        ReceiptBillingLayout.setHorizontalGroup(
            ReceiptBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        ReceiptBillingLayout.setVerticalGroup(
            ReceiptBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout RevenueLayout = new javax.swing.GroupLayout(Revenue);
        Revenue.setLayout(RevenueLayout);
        RevenueLayout.setHorizontalGroup(
            RevenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        RevenueLayout.setVerticalGroup(
            RevenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1200, 700));

        tableInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(tableInfo);

        backHomePage.setText("jButton1");
        backHomePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backHomePageActionPerformed(evt);
            }
        });

        addRoom.setText("ADD ROOM");
        addRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRoomActionPerformed(evt);
            }
        });

        exitBnt.setText("jButton3");
        exitBnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBntActionPerformed(evt);
            }
        });

        textField1.setText("textField1");
        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(backHomePage))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                .addComponent(exitBnt)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exitBnt)
                    .addComponent(backHomePage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backHomePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backHomePageActionPerformed
        // TODO add your handling code here:
       // new 
    }//GEN-LAST:event_backHomePageActionPerformed

    private void exitBntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBntActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitBntActionPerformed

    private void addRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addRoomActionPerformed

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed
    private void addRightClickMenu() {
    // Popup menu
    JPopupMenu popup = new JPopupMenu();

    JMenuItem editItem = new JMenuItem("Edit");
    JMenuItem deleteItem = new JMenuItem("Delete");

    popup.add(editItem);
    popup.add(deleteItem);

    // Mouse listener for right-click
    tableInfo.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mousePressed(java.awt.event.MouseEvent e) {
            showPopup(e);
        }

        @Override
        public void mouseReleased(java.awt.event.MouseEvent e) {
            showPopup(e);
        }

        private void showPopup(java.awt.event.MouseEvent e) {
            if (e.isPopupTrigger()) { // Right click
                int row = tableInfo.rowAtPoint(e.getPoint());
                tableInfo.setRowSelectionInterval(row, row); // highlight row
                popup.show(e.getComponent(), e.getX(), e.getY());
            }
        }
    });

    // EDIT ACTION
    editItem.addActionListener(e -> {
        int selected = tableInfo.getSelectedRow();
        if (selected != -1) {
            System.out.println("Edit row: " + selected);
            // YOU CAN OPEN A NEW FORM OR EDIT DIALOG HERE
        }
    });

    // DELETE ACTION
    deleteItem.addActionListener(e -> {
        int selected = tableInfo.getSelectedRow();
        if (selected != -1) {
            ((javax.swing.table.DefaultTableModel) tableInfo.getModel()).removeRow(selected);
        }
    });
}

    /**
     * @param args the command line arguments
     */
    
     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NewJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CheckIn;
    private javax.swing.JPanel CheckOut;
    private javax.swing.JPanel ManageRoom;
    private javax.swing.JPanel ReceiptBilling;
    private javax.swing.JPanel Revenue;
    private javax.swing.JButton addRoom;
    private javax.swing.JButton backHomePage;
    private javax.swing.JButton exitBnt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableInfo;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
